/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as SettingsRouteRouteImport } from './routes/settings/route'
import { Route as OnboardingRouteRouteImport } from './routes/onboarding/route'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as OnboardingIndexRouteImport } from './routes/onboarding/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as AuthVerifyPhoneRouteImport } from './routes/auth/verify-phone'
import { Route as AuthVerifyEmailRouteImport } from './routes/auth/verify-email'
import { Route as AuthResetPasswordSuccessRouteImport } from './routes/auth/reset-password-success'
import { Route as AuthResetPasswordOtpRouteImport } from './routes/auth/reset-password-otp'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as AuthCheckEmailResetRouteImport } from './routes/auth/check-email-reset'
import { Route as AuthCheckEmailRegisterRouteImport } from './routes/auth/check-email-register'
import { Route as DashboardStationStationIdRouteImport } from './routes/dashboard/station.$stationId'
import { Route as DashboardAccountPhoneRouteImport } from './routes/dashboard/account.phone'
import { Route as DashboardStationStationIdShiftsRouteImport } from './routes/dashboard/station.$stationId.shifts'
import { Route as DashboardStationStationIdSetupRouteImport } from './routes/dashboard/station.$stationId.setup'
import { Route as DashboardStationStationIdReportsRouteImport } from './routes/dashboard/station.$stationId.reports'
import { Route as DashboardStationStationIdInventoryRouteImport } from './routes/dashboard/station.$stationId.inventory'
import { Route as DashboardStationStationIdFinanceRouteImport } from './routes/dashboard/station.$stationId.finance'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRouteRoute = SettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRouteRoute = OnboardingRouteRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const OnboardingIndexRoute = OnboardingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const AuthVerifyPhoneRoute = AuthVerifyPhoneRouteImport.update({
  id: '/verify-phone',
  path: '/verify-phone',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthVerifyEmailRoute = AuthVerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthResetPasswordSuccessRoute =
  AuthResetPasswordSuccessRouteImport.update({
    id: '/reset-password-success',
    path: '/reset-password-success',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const AuthResetPasswordOtpRoute = AuthResetPasswordOtpRouteImport.update({
  id: '/reset-password-otp',
  path: '/reset-password-otp',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthCheckEmailResetRoute = AuthCheckEmailResetRouteImport.update({
  id: '/check-email-reset',
  path: '/check-email-reset',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthCheckEmailRegisterRoute = AuthCheckEmailRegisterRouteImport.update({
  id: '/check-email-register',
  path: '/check-email-register',
  getParentRoute: () => AuthRouteRoute,
} as any)
const DashboardStationStationIdRoute =
  DashboardStationStationIdRouteImport.update({
    id: '/station/$stationId',
    path: '/station/$stationId',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardAccountPhoneRoute = DashboardAccountPhoneRouteImport.update({
  id: '/account/phone',
  path: '/account/phone',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardStationStationIdShiftsRoute =
  DashboardStationStationIdShiftsRouteImport.update({
    id: '/shifts',
    path: '/shifts',
    getParentRoute: () => DashboardStationStationIdRoute,
  } as any)
const DashboardStationStationIdSetupRoute =
  DashboardStationStationIdSetupRouteImport.update({
    id: '/setup',
    path: '/setup',
    getParentRoute: () => DashboardStationStationIdRoute,
  } as any)
const DashboardStationStationIdReportsRoute =
  DashboardStationStationIdReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => DashboardStationStationIdRoute,
  } as any)
const DashboardStationStationIdInventoryRoute =
  DashboardStationStationIdInventoryRouteImport.update({
    id: '/inventory',
    path: '/inventory',
    getParentRoute: () => DashboardStationStationIdRoute,
  } as any)
const DashboardStationStationIdFinanceRoute =
  DashboardStationStationIdFinanceRouteImport.update({
    id: '/finance',
    path: '/finance',
    getParentRoute: () => DashboardStationStationIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/onboarding': typeof OnboardingRouteRouteWithChildren
  '/settings': typeof SettingsRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth/check-email-register': typeof AuthCheckEmailRegisterRoute
  '/auth/check-email-reset': typeof AuthCheckEmailResetRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/reset-password-otp': typeof AuthResetPasswordOtpRoute
  '/auth/reset-password-success': typeof AuthResetPasswordSuccessRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/auth/verify-phone': typeof AuthVerifyPhoneRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/dashboard/account/phone': typeof DashboardAccountPhoneRoute
  '/dashboard/station/$stationId': typeof DashboardStationStationIdRouteWithChildren
  '/dashboard/station/$stationId/finance': typeof DashboardStationStationIdFinanceRoute
  '/dashboard/station/$stationId/inventory': typeof DashboardStationStationIdInventoryRoute
  '/dashboard/station/$stationId/reports': typeof DashboardStationStationIdReportsRoute
  '/dashboard/station/$stationId/setup': typeof DashboardStationStationIdSetupRoute
  '/dashboard/station/$stationId/shifts': typeof DashboardStationStationIdShiftsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth/check-email-register': typeof AuthCheckEmailRegisterRoute
  '/auth/check-email-reset': typeof AuthCheckEmailResetRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/reset-password-otp': typeof AuthResetPasswordOtpRoute
  '/auth/reset-password-success': typeof AuthResetPasswordSuccessRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/auth/verify-phone': typeof AuthVerifyPhoneRoute
  '/dashboard': typeof DashboardIndexRoute
  '/onboarding': typeof OnboardingIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/dashboard/account/phone': typeof DashboardAccountPhoneRoute
  '/dashboard/station/$stationId': typeof DashboardStationStationIdRouteWithChildren
  '/dashboard/station/$stationId/finance': typeof DashboardStationStationIdFinanceRoute
  '/dashboard/station/$stationId/inventory': typeof DashboardStationStationIdInventoryRoute
  '/dashboard/station/$stationId/reports': typeof DashboardStationStationIdReportsRoute
  '/dashboard/station/$stationId/setup': typeof DashboardStationStationIdSetupRoute
  '/dashboard/station/$stationId/shifts': typeof DashboardStationStationIdShiftsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/onboarding': typeof OnboardingRouteRouteWithChildren
  '/settings': typeof SettingsRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth/check-email-register': typeof AuthCheckEmailRegisterRoute
  '/auth/check-email-reset': typeof AuthCheckEmailResetRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/reset-password-otp': typeof AuthResetPasswordOtpRoute
  '/auth/reset-password-success': typeof AuthResetPasswordSuccessRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/auth/verify-phone': typeof AuthVerifyPhoneRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/dashboard/account/phone': typeof DashboardAccountPhoneRoute
  '/dashboard/station/$stationId': typeof DashboardStationStationIdRouteWithChildren
  '/dashboard/station/$stationId/finance': typeof DashboardStationStationIdFinanceRoute
  '/dashboard/station/$stationId/inventory': typeof DashboardStationStationIdInventoryRoute
  '/dashboard/station/$stationId/reports': typeof DashboardStationStationIdReportsRoute
  '/dashboard/station/$stationId/setup': typeof DashboardStationStationIdSetupRoute
  '/dashboard/station/$stationId/shifts': typeof DashboardStationStationIdShiftsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/onboarding'
    | '/settings'
    | '/about'
    | '/auth/check-email-register'
    | '/auth/check-email-reset'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/auth/reset-password-otp'
    | '/auth/reset-password-success'
    | '/auth/verify-email'
    | '/auth/verify-phone'
    | '/dashboard/'
    | '/onboarding/'
    | '/settings/'
    | '/dashboard/account/phone'
    | '/dashboard/station/$stationId'
    | '/dashboard/station/$stationId/finance'
    | '/dashboard/station/$stationId/inventory'
    | '/dashboard/station/$stationId/reports'
    | '/dashboard/station/$stationId/setup'
    | '/dashboard/station/$stationId/shifts'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/about'
    | '/auth/check-email-register'
    | '/auth/check-email-reset'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/auth/reset-password-otp'
    | '/auth/reset-password-success'
    | '/auth/verify-email'
    | '/auth/verify-phone'
    | '/dashboard'
    | '/onboarding'
    | '/settings'
    | '/dashboard/account/phone'
    | '/dashboard/station/$stationId'
    | '/dashboard/station/$stationId/finance'
    | '/dashboard/station/$stationId/inventory'
    | '/dashboard/station/$stationId/reports'
    | '/dashboard/station/$stationId/setup'
    | '/dashboard/station/$stationId/shifts'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard'
    | '/onboarding'
    | '/settings'
    | '/about'
    | '/auth/check-email-register'
    | '/auth/check-email-reset'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/auth/reset-password-otp'
    | '/auth/reset-password-success'
    | '/auth/verify-email'
    | '/auth/verify-phone'
    | '/dashboard/'
    | '/onboarding/'
    | '/settings/'
    | '/dashboard/account/phone'
    | '/dashboard/station/$stationId'
    | '/dashboard/station/$stationId/finance'
    | '/dashboard/station/$stationId/inventory'
    | '/dashboard/station/$stationId/reports'
    | '/dashboard/station/$stationId/setup'
    | '/dashboard/station/$stationId/shifts'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  OnboardingRouteRoute: typeof OnboardingRouteRouteWithChildren
  SettingsRouteRoute: typeof SettingsRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/onboarding/': {
      id: '/onboarding/'
      path: '/'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof OnboardingIndexRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/auth/verify-phone': {
      id: '/auth/verify-phone'
      path: '/verify-phone'
      fullPath: '/auth/verify-phone'
      preLoaderRoute: typeof AuthVerifyPhoneRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/verify-email': {
      id: '/auth/verify-email'
      path: '/verify-email'
      fullPath: '/auth/verify-email'
      preLoaderRoute: typeof AuthVerifyEmailRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/reset-password-success': {
      id: '/auth/reset-password-success'
      path: '/reset-password-success'
      fullPath: '/auth/reset-password-success'
      preLoaderRoute: typeof AuthResetPasswordSuccessRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/reset-password-otp': {
      id: '/auth/reset-password-otp'
      path: '/reset-password-otp'
      fullPath: '/auth/reset-password-otp'
      preLoaderRoute: typeof AuthResetPasswordOtpRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/check-email-reset': {
      id: '/auth/check-email-reset'
      path: '/check-email-reset'
      fullPath: '/auth/check-email-reset'
      preLoaderRoute: typeof AuthCheckEmailResetRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/check-email-register': {
      id: '/auth/check-email-register'
      path: '/check-email-register'
      fullPath: '/auth/check-email-register'
      preLoaderRoute: typeof AuthCheckEmailRegisterRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/dashboard/station/$stationId': {
      id: '/dashboard/station/$stationId'
      path: '/station/$stationId'
      fullPath: '/dashboard/station/$stationId'
      preLoaderRoute: typeof DashboardStationStationIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/account/phone': {
      id: '/dashboard/account/phone'
      path: '/account/phone'
      fullPath: '/dashboard/account/phone'
      preLoaderRoute: typeof DashboardAccountPhoneRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/station/$stationId/shifts': {
      id: '/dashboard/station/$stationId/shifts'
      path: '/shifts'
      fullPath: '/dashboard/station/$stationId/shifts'
      preLoaderRoute: typeof DashboardStationStationIdShiftsRouteImport
      parentRoute: typeof DashboardStationStationIdRoute
    }
    '/dashboard/station/$stationId/setup': {
      id: '/dashboard/station/$stationId/setup'
      path: '/setup'
      fullPath: '/dashboard/station/$stationId/setup'
      preLoaderRoute: typeof DashboardStationStationIdSetupRouteImport
      parentRoute: typeof DashboardStationStationIdRoute
    }
    '/dashboard/station/$stationId/reports': {
      id: '/dashboard/station/$stationId/reports'
      path: '/reports'
      fullPath: '/dashboard/station/$stationId/reports'
      preLoaderRoute: typeof DashboardStationStationIdReportsRouteImport
      parentRoute: typeof DashboardStationStationIdRoute
    }
    '/dashboard/station/$stationId/inventory': {
      id: '/dashboard/station/$stationId/inventory'
      path: '/inventory'
      fullPath: '/dashboard/station/$stationId/inventory'
      preLoaderRoute: typeof DashboardStationStationIdInventoryRouteImport
      parentRoute: typeof DashboardStationStationIdRoute
    }
    '/dashboard/station/$stationId/finance': {
      id: '/dashboard/station/$stationId/finance'
      path: '/finance'
      fullPath: '/dashboard/station/$stationId/finance'
      preLoaderRoute: typeof DashboardStationStationIdFinanceRouteImport
      parentRoute: typeof DashboardStationStationIdRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthCheckEmailRegisterRoute: typeof AuthCheckEmailRegisterRoute
  AuthCheckEmailResetRoute: typeof AuthCheckEmailResetRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthResetPasswordOtpRoute: typeof AuthResetPasswordOtpRoute
  AuthResetPasswordSuccessRoute: typeof AuthResetPasswordSuccessRoute
  AuthVerifyEmailRoute: typeof AuthVerifyEmailRoute
  AuthVerifyPhoneRoute: typeof AuthVerifyPhoneRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthCheckEmailRegisterRoute: AuthCheckEmailRegisterRoute,
  AuthCheckEmailResetRoute: AuthCheckEmailResetRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthResetPasswordOtpRoute: AuthResetPasswordOtpRoute,
  AuthResetPasswordSuccessRoute: AuthResetPasswordSuccessRoute,
  AuthVerifyEmailRoute: AuthVerifyEmailRoute,
  AuthVerifyPhoneRoute: AuthVerifyPhoneRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface DashboardStationStationIdRouteChildren {
  DashboardStationStationIdFinanceRoute: typeof DashboardStationStationIdFinanceRoute
  DashboardStationStationIdInventoryRoute: typeof DashboardStationStationIdInventoryRoute
  DashboardStationStationIdReportsRoute: typeof DashboardStationStationIdReportsRoute
  DashboardStationStationIdSetupRoute: typeof DashboardStationStationIdSetupRoute
  DashboardStationStationIdShiftsRoute: typeof DashboardStationStationIdShiftsRoute
}

const DashboardStationStationIdRouteChildren: DashboardStationStationIdRouteChildren =
  {
    DashboardStationStationIdFinanceRoute:
      DashboardStationStationIdFinanceRoute,
    DashboardStationStationIdInventoryRoute:
      DashboardStationStationIdInventoryRoute,
    DashboardStationStationIdReportsRoute:
      DashboardStationStationIdReportsRoute,
    DashboardStationStationIdSetupRoute: DashboardStationStationIdSetupRoute,
    DashboardStationStationIdShiftsRoute: DashboardStationStationIdShiftsRoute,
  }

const DashboardStationStationIdRouteWithChildren =
  DashboardStationStationIdRoute._addFileChildren(
    DashboardStationStationIdRouteChildren,
  )

interface DashboardRouteRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardAccountPhoneRoute: typeof DashboardAccountPhoneRoute
  DashboardStationStationIdRoute: typeof DashboardStationStationIdRouteWithChildren
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardAccountPhoneRoute: DashboardAccountPhoneRoute,
  DashboardStationStationIdRoute: DashboardStationStationIdRouteWithChildren,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

interface OnboardingRouteRouteChildren {
  OnboardingIndexRoute: typeof OnboardingIndexRoute
}

const OnboardingRouteRouteChildren: OnboardingRouteRouteChildren = {
  OnboardingIndexRoute: OnboardingIndexRoute,
}

const OnboardingRouteRouteWithChildren = OnboardingRouteRoute._addFileChildren(
  OnboardingRouteRouteChildren,
)

interface SettingsRouteRouteChildren {
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteRouteChildren: SettingsRouteRouteChildren = {
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteRouteWithChildren = SettingsRouteRoute._addFileChildren(
  SettingsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  OnboardingRouteRoute: OnboardingRouteRouteWithChildren,
  SettingsRouteRoute: SettingsRouteRouteWithChildren,
  AboutRoute: AboutRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
